// Code generated by protoc-gen-go.
// source: github.com/micro/router-srv/proto/label/label.proto
// DO NOT EDIT!

/*
Package label is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/router-srv/proto/label/label.proto

It has these top-level messages:
	LabelSet
	ReadRequest
	ReadResponse
	CreateRequest
	CreateResponse
	UpdateRequest
	UpdateResponse
	DeleteRequest
	DeleteResponse
	SearchRequest
	SearchResponse
*/
package label

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type LabelSet struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// the service name
	Service string `protobuf:"bytes,2,opt,name=service" json:"service,omitempty"`
	// optional: service version
	Version string `protobuf:"bytes,3,opt,name=version" json:"version,omitempty"`
	// weight between 0 and 100
	// 0 removes the key-value from all nodes
	// 100 adds the key-value to all nodes
	// or nodes specified with node_ids
	Weight int64 `protobuf:"varint,4,opt,name=weight" json:"weight,omitempty"`
	// optional: priority of this label
	// 0 is highest
	Priority int64 `protobuf:"varint,5,opt,name=priority" json:"priority,omitempty"`
	// label name
	Key string `protobuf:"bytes,6,opt,name=key" json:"key,omitempty"`
	// label value
	Value string `protobuf:"bytes,7,opt,name=value" json:"value,omitempty"`
}

func (m *LabelSet) Reset()                    { *m = LabelSet{} }
func (m *LabelSet) String() string            { return proto.CompactTextString(m) }
func (*LabelSet) ProtoMessage()               {}
func (*LabelSet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ReadRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ReadResponse struct {
	Label *LabelSet `protobuf:"bytes,1,opt,name=label" json:"label,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ReadResponse) GetLabel() *LabelSet {
	if m != nil {
		return m.Label
	}
	return nil
}

type CreateRequest struct {
	Label *LabelSet `protobuf:"bytes,1,opt,name=label" json:"label,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CreateRequest) GetLabel() *LabelSet {
	if m != nil {
		return m.Label
	}
	return nil
}

type CreateResponse struct {
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type UpdateRequest struct {
	Label *LabelSet `protobuf:"bytes,1,opt,name=label" json:"label,omitempty"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UpdateRequest) GetLabel() *LabelSet {
	if m != nil {
		return m.Label
	}
	return nil
}

type UpdateResponse struct {
}

func (m *UpdateResponse) Reset()                    { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()               {}
func (*UpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type DeleteRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type DeleteResponse struct {
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type SearchRequest struct {
	// optional params
	Service string `protobuf:"bytes,1,opt,name=service" json:"service,omitempty"`
	Key     string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Limit   int64  `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	Offset  int64  `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type SearchResponse struct {
	Labels []*LabelSet `protobuf:"bytes,1,rep,name=labels" json:"labels,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *SearchResponse) GetLabels() []*LabelSet {
	if m != nil {
		return m.Labels
	}
	return nil
}

func init() {
	proto.RegisterType((*LabelSet)(nil), "LabelSet")
	proto.RegisterType((*ReadRequest)(nil), "ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "ReadResponse")
	proto.RegisterType((*CreateRequest)(nil), "CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "CreateResponse")
	proto.RegisterType((*UpdateRequest)(nil), "UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "DeleteResponse")
	proto.RegisterType((*SearchRequest)(nil), "SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "SearchResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Label service

type LabelClient interface {
	Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error)
	Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error)
}

type labelClient struct {
	c           client.Client
	serviceName string
}

func NewLabelClient(serviceName string, c client.Client) LabelClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "label"
	}
	return &labelClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *labelClient) Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Label.Read", in)
	out := new(ReadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *labelClient) Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Label.Create", in)
	out := new(CreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *labelClient) Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Label.Update", in)
	out := new(UpdateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *labelClient) Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Label.Delete", in)
	out := new(DeleteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *labelClient) Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Label.Search", in)
	out := new(SearchResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Label service

type LabelHandler interface {
	Read(context.Context, *ReadRequest, *ReadResponse) error
	Create(context.Context, *CreateRequest, *CreateResponse) error
	Update(context.Context, *UpdateRequest, *UpdateResponse) error
	Delete(context.Context, *DeleteRequest, *DeleteResponse) error
	Search(context.Context, *SearchRequest, *SearchResponse) error
}

func RegisterLabelHandler(s server.Server, hdlr LabelHandler) {
	s.Handle(s.NewHandler(&Label{hdlr}))
}

type Label struct {
	LabelHandler
}

func (h *Label) Read(ctx context.Context, in *ReadRequest, out *ReadResponse) error {
	return h.LabelHandler.Read(ctx, in, out)
}

func (h *Label) Create(ctx context.Context, in *CreateRequest, out *CreateResponse) error {
	return h.LabelHandler.Create(ctx, in, out)
}

func (h *Label) Update(ctx context.Context, in *UpdateRequest, out *UpdateResponse) error {
	return h.LabelHandler.Update(ctx, in, out)
}

func (h *Label) Delete(ctx context.Context, in *DeleteRequest, out *DeleteResponse) error {
	return h.LabelHandler.Delete(ctx, in, out)
}

func (h *Label) Search(ctx context.Context, in *SearchRequest, out *SearchResponse) error {
	return h.LabelHandler.Search(ctx, in, out)
}

var fileDescriptor0 = []byte{
	// 375 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0xca, 0xda, 0x40,
	0x10, 0x80, 0x7f, 0xcd, 0x9f, 0xa8, 0xa3, 0x89, 0xb2, 0xa7, 0xd5, 0x5e, 0x4a, 0xa0, 0x60, 0x91,
	0x26, 0xa0, 0x8f, 0xd0, 0x1e, 0x3d, 0x29, 0x7d, 0x80, 0x18, 0x47, 0x5d, 0x1a, 0xdd, 0x74, 0x77,
	0x93, 0xe2, 0xeb, 0xf6, 0x49, 0xba, 0xd9, 0xcd, 0xd2, 0x44, 0x28, 0xf4, 0x12, 0x98, 0x99, 0x6f,
	0x26, 0x33, 0x1f, 0x0b, 0xbb, 0x2b, 0x53, 0xb7, 0xea, 0x94, 0xe4, 0xfc, 0x9e, 0xde, 0x59, 0x2e,
	0x78, 0x2a, 0x78, 0xa5, 0x50, 0x7c, 0x91, 0xa2, 0x4e, 0x4b, 0xc1, 0x15, 0x4f, 0x8b, 0xec, 0x84,
	0x85, 0xfd, 0x26, 0x26, 0x13, 0xd7, 0x30, 0xde, 0x37, 0xe1, 0x11, 0x15, 0x01, 0x18, 0xb2, 0x33,
	0x1d, 0x7c, 0x1c, 0xac, 0x27, 0x64, 0x0e, 0x23, 0x89, 0xa2, 0x66, 0x39, 0xd2, 0xa1, 0x4b, 0xd4,
	0x28, 0x24, 0xe3, 0x0f, 0xea, 0x99, 0x44, 0x04, 0xc1, 0x2f, 0x64, 0xd7, 0x9b, 0xa2, 0xef, 0x3a,
	0xf6, 0xc8, 0x02, 0xc6, 0xa5, 0x60, 0x5c, 0x30, 0xf5, 0xa4, 0xbe, 0xc9, 0x4c, 0xc1, 0xfb, 0x81,
	0x4f, 0x1a, 0x18, 0x3c, 0x04, 0xbf, 0xce, 0x8a, 0x0a, 0xe9, 0xa8, 0x09, 0xe3, 0x25, 0x4c, 0x0f,
	0x98, 0x9d, 0x0f, 0xf8, 0xb3, 0x42, 0xd9, 0xfb, 0x75, 0xbc, 0x86, 0x99, 0x2d, 0xc9, 0x92, 0x3f,
	0x24, 0x12, 0x0a, 0xbe, 0xd9, 0xd8, 0x94, 0xa7, 0xdb, 0x49, 0xe2, 0x16, 0x8e, 0x3f, 0x43, 0xf8,
	0x55, 0x60, 0xa6, 0xd0, 0x8d, 0xf9, 0x37, 0xba, 0x80, 0xc8, 0xa1, 0x76, 0x6c, 0xd3, 0xfc, 0xbd,
	0x3c, 0xff, 0x6f, 0xb3, 0x43, 0xdb, 0xe6, 0x0f, 0x10, 0x7e, 0xc3, 0x02, 0xff, 0x36, 0x77, 0x0f,
	0xd0, 0xb8, 0x2b, 0xb6, 0xf8, 0x1e, 0xc2, 0x23, 0x66, 0x22, 0xbf, 0x39, 0xbc, 0xa3, 0xd7, 0xfa,
	0x6e, 0x5d, 0x0d, 0x9d, 0xab, 0x82, 0xdd, 0x99, 0x32, 0xa6, 0xbd, 0xc6, 0x34, 0xbf, 0x5c, 0x24,
	0xb6, 0xa6, 0xe3, 0x0d, 0x44, 0x6e, 0x5a, 0xab, 0x68, 0x09, 0x81, 0x59, 0x5d, 0xea, 0x69, 0x5e,
	0x6f, 0xf7, 0xed, 0xef, 0x01, 0xf8, 0x26, 0x20, 0x9f, 0xe0, 0xbd, 0xf1, 0x4a, 0x66, 0x49, 0xc7,
	0xfc, 0x2a, 0x4c, 0xba, 0xb2, 0xe3, 0x37, 0xb2, 0x81, 0xc0, 0x9a, 0x22, 0x51, 0xd2, 0xb3, 0xbb,
	0x9a, 0x27, 0x2f, 0x0a, 0x0d, 0x6c, 0xcd, 0x68, 0xb8, 0x67, 0x53, 0xc3, 0x2f, 0xca, 0x0c, 0x6c,
	0xbd, 0x68, 0xb8, 0x67, 0x4f, 0xc3, 0x2f, 0xc2, 0x0c, 0x6c, 0x8f, 0xd4, 0x70, 0xcf, 0x9d, 0x86,
	0xfb, 0xd7, 0xc7, 0x6f, 0xa7, 0xc0, 0x3c, 0xe6, 0xdd, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x67,
	0x6f, 0x13, 0x00, 0x03, 0x03, 0x00, 0x00,
}
